[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "slinn"
version = "3.0.0a8"
description = "An HTTP server framework"
readme = "README.md"
requires-python = ">=3.15"
dependencies = [
    "tomlkit==0.15.1",
    "orjson>=3.11.9",
    "babel>=2.18.0",
    "pydantic>=2.14.0b1"
]
authors = [
    { name = "Miot Project", email = "openmiot@gmail.com"},
    { name = "Mark Radin", email = "mrybs2@gmail.com" }
]
urls = { Homepage = "https://wiki.miot.su/slinn" }

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-describe>=3.2.0",
    "pytest-mock>=3.15.1",
    "pytest-cov>=7.1.0",
    "taskipy>=1.14.1",
    "poetry>=2.4.1"
]
alt_loop = [
    "uvloop>=0.22.1; sys_platform != 'win32'",
    "winloop>=0.6.3; sys_platform == 'win32'",
]

[project.scripts]
slinn-admin = "slinn.scripts.slinn_admin:main"
slinn       = "slinn.scripts.slinn:main"
spm         = "slinn.scripts.spm:main"

[tool.setuptools]
zip-safe = false
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = ["t*", "venv*", "Writerside*", "build*", "test*", ".venv*"]

[tool.pytest.ini_options]
addopts = "-v --cov=slinn --cov-report=html --cov-fail-under=80"
filterwarnings = [
    "ignore::UserWarning"
]

[tool.taskipy.settings]
cwd = "."

[tool.taskipy.tasks]
i18n_update  = """pybabel extract -o slinn/locales/messages.pot . &&\
                pybabel update -i slinn/locales/messages.pot -d slinn/locales"""
i18n_compile = "pybabel compile -d slinn/locales"
build = "poetry build"
publish = "poetry publish"

