[build-system]
requires = ["pybind11>=3.1.0", "scikit-build-core>=1.0.3"]
build-backend = "scikit_build_core.build"

[project]
name = "slinn"
version = "3.0.0a11"
description = "An HTTP server framework"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.15"
dependencies = [
    "tomlkit==0.15.1",
    "orjson>=3.11.9",
    "babel>=2.18.0",
    "pydantic>=2.14.0b1"
]
authors = [
    { name = "Miot Project", email = "openmiot@gmail.com"},
    { name = "Mark Radin", email = "mrybs2@gmail.com" }
]
urls = { Homepage = "https://openimot.github.io/slinn" }
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: C++",

    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",

    "Topic :: Internet",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",

    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Framework :: AsyncIO",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-describe>=3.2.0",
    "pytest-mock>=3.15.1",
    "pytest-cov>=7.1.0",
    "taskipy>=1.14.1",
    "poetry>=2.4.1",
    "zensical>=0.0.53",
    "pyrefly>=1.2.0",
]
alt_loop = [
    "uvloop>=0.22.1; sys_platform != 'win32'",
    "winloop>=0.6.3; sys_platform == 'win32'",
]

[project.scripts]
slinn-admin = "slinn.scripts.slinn_admin:main"
slinn       = "slinn.scripts.slinn:main"
spm         = "slinn.scripts.spm:main"

[tool.scikit-build]
cmake.version = ">=3.15"
cmake.build-type = "Release"
wheel.expand-macos-universal-tags = true
build-dir = "build"

[tool.scikit-build.editable]
mode = "redirect"           # вместо "inplace" – сборка в build/ и симлинки
rebuild = false             # не пересобирать при повторной установке, если ничего не изменилось

[tool.pytest.ini_options]
addopts = "-v --cov=slinn --cov-report=html --cov-fail-under=80"
filterwarnings = [
    "ignore::UserWarning"
]

[tool.taskipy.settings]
cwd = "."

[tool.taskipy.tasks]
i18n_update  = """pybabel extract -o slinn/locales/messages.pot . &&\
                pybabel update -i slinn/locales/messages.pot -d slinn/locales"""
i18n_compile = "pybabel compile -d slinn/locales"
build = "poetry build"
publish = "poetry publish"

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

