[project]
name = "Slinn"
display_name = "Project running on Slinn"
version = "1.0.0"
description = "My awesome Slinn project"
debug = true

[[addresses]]
name = "main"
port = "8080/tcp"
host = "localhost"
domains = [
    "localhost",
    "127.0.0.1",
    "::1"
]
protocol = "http"
tls = false

[[apps]]
name = "firstrun"
enabled = true
debug_only = true
portmap = {
    80 = "main"
}

[tls]
default_fullchain = false
default_privkey = false

[protocols.tcp]
timeout = 0.5
max_timeout = 60
max_bytes_per_receive = 65535

[protocols.http]
max_header_size = 8192

[protocols.websocket]
max_frame_size = 65535
ping_interval = 30

[protocols.quic]
idle_timeout = 60

[logging]
level = "info"
format = "json"
output = "stdout"
